Fixing according to CR
itye-msft/Autom8s pull request #19
Opened 2018-08-05 12:52 UTC by eladiw

2018-08-09 11:52 UTC, limorl commented on README.md
> -# Project Autom8s - Automation for K8S
I am not sure 'automation for K8s reflects what this repo does, you should consider another title and repo name

2018-08-09 11:52 UTC, limorl commented on README.md
> +Here is a quick node.js snippet that makes use of the API to install RabbitMQ with default settings. Note: any chart will be suitable, RabbitMQ is just a specific example:
'Note: ...' in a new line

2018-08-09 11:52 UTC, limorl commented on README.md
>  return "Your new service: " + ingressResponse.releaseName + ", is publicly accessibly on " + ingressResponse.ip + ":" + ingressResponse.port;
publicly accessible (instead of accessibly)

2018-08-09 11:52 UTC, limorl commented on README.md
>  return "Your new service: " + ingressResponse.releaseName + ", is publicly accessibly on " + ingressResponse.ip + ":" + ingressResponse.port;
please use format

2018-08-09 11:52 UTC, limorl commented on autom8s/helm-controller.js
> + */
Here and everywhere else: when writing a service and returning an HTTP error, don't expose the internal error and avoid returning it. It is not a good practice.
 You should log the error, and if you have a user understandable error message, you may return it.

2018-08-09 11:52 UTC, limorl commented on autom8s/helm.js
> +      console.log(`using a user chosen release name: ${releaseName}`);
change log to: installing specified release name: ${releaseName}

2018-08-09 11:52 UTC, limorl commented on autom8s/helm.js
> -    return this._innerInstallUpgrade(installCommand, deployOptions)
remove the prefix 'inner' from every method. The '_' prefix indicates that

2018-08-09 11:52 UTC, limorl commented on autom8s/helm.js
>            throw new Error(`Install command failed: ${responseData.error}`);
don't you want to log the error?

2018-08-09 11:52 UTC, limorl commented on autom8s/helm.js
> +    Helm._verifyNotEmpty(chartName, 'chartName');
better rename to _validateNotEmpty or _assertNotEmpty - which is more conventional

2018-08-09 11:52 UTC, limorl commented on autom8s/helm.js
> +      const errorMsg = `${argName} is mandatory`;
change 'mandatory' to 'required' whch is more conventional (e.g. required or optional parameters)

2018-08-09 11:52 UTC, limorl commented on autom8s/helm.js
>    static _findFirstService(json) {
Not clear to me why you are searching for v1/Service. will it always be v1?

2018-08-09 11:52 UTC, limorl commented on autom8s/ingress-controller.js
>        specificlb,
the prefix 'specific' is redundant

2018-08-09 11:52 UTC, limorl commented on index.js
> +app.use('/', ingressController);
I have told Itye that a better practice would be to have all the HTTP commands here (app.post, app.get, etc.) which makes very clear what is the API. And then you don't have xxx-service, but rather just xxx classes..
app.use hides the interface. 
I don't like it.

2018-08-12 08:02 UTC, eladiw reviewed
Pushed new commit with all the fixes

2018-08-12 08:02 UTC, eladiw commented on README.md
> -# Project Autom8s - Automation for K8S
Agree, the new name is : "Helm Charts installation through http endpoints"

2018-08-12 08:02 UTC, eladiw commented on autom8s/helm.js
> -    return this._innerInstallUpgrade(installCommand, deployOptions)
It is already removed (note the red marking on that line)

2018-08-12 08:02 UTC, eladiw commented on autom8s/helm.js
>    static _findFirstService(json) {
Currently yes, v1/service is the only option (up to k8s 1.11). however, i made it more robust by ignoring the version section

2018-08-13 06:16 UTC, limorl approved these changes

2018-08-13 06:16 UTC, limorl commented on index.js
> +app.post('/install',
BTW, you could still keep the logic in the port-controller, ingress-controller objects, etc, and only extract the http service related functionality under app.post, app.get, etc.

My comment was about making sure the api is clear from going over the index.js file without having to go over 4 different files.

2018-08-16 10:29 UTC, torosent requested changes

2018-08-16 10:29 UTC, torosent commented on README.md
> +**Ingres rule setter**: expose installed helm charts to the internet, via a single IP.
Ingress

2018-08-16 10:29 UTC, torosent commented on README.md
> +    kubectl apply -f https://raw.githubusercontent.com/itye-msft/kubernetes-dynamic-deployment-service/master/rbac-example/tiller.yaml
this link will change once you transfer repo

2018-08-16 10:29 UTC, torosent commented on README.md
> +## Contributing
This should have an official MS OSS notice

2018-08-16 11:21 UTC, merged